### PR TITLE
AutoTotem fix + add Boat Fly + add Jesus + CrystalAura (read details)

### PR DESCRIPTION
**Pull request by ren7995**
- Changes Scaffold to switch back to the originally held item stack
- Fixes issues with AutoTotem where the totem would be picked up when opening inventory but could not be placed back into a slot

### CODE REVIEW

**Comment by ren7995** [comment]
- Added BoatFly
- Added Jesus

**Comment by ren7995** [comment]
Video preview: https://imgur.com/a/TTLjM4X

**Review by majorsopa — APPROVED** [review]
nice

**Comment by ren7995** [comment]
Just changed the following:
- Fixed a possible client crash with kill aura 
- Added option to attack all entities with kill aura (excluding crystals)
- Added CrystalAura

**Comment by evaan** [comment]
good shit thanks burrit0z

**Comment by ren7995** [comment]
I'll add config saving + presets too when I get a chance

**Pull request merged**
